Routepath : routes
Mockpath : webmock
Templatepath : views

Defined:
    root : wwwroot
    app : app

Includes:
    - configure/root_route.yaml
    - configure/user_route.yaml
    - configure/proxy_route.yaml