Port : 8000
Routepath : routes
Mockpath : test\mock
Staticpath : statics
Templatepath : views

Whatchupdate : false

Defined:
    root : wwwroot
    app : app
    controller : app/controller

Includes:
    - configure/root_route.yaml
    - configure/user_route.yaml
    - configure/proxy_route.yaml
    - configure/mock_route.yaml